kind: pipeline
name: Kernel Compile
clone:
  depth: 1
steps:
 - name: compile
   image: diazaji/python:focal
   environment:
     TELEGRAM_TOKEN:
       from_secret: TELEGRAM_TOKEN
   commands:
      - cd /drone/src
      - wget https://raw.githubusercontent.com/Diaz1401/build_script/alioth/build-gcc.sh
      - bash build-gcc.sh latest
